import { FormEvent, useEffect, useState } from 'react'
import { Plus, UserPlus, X } from 'lucide-react'
import { supabase } from './lib/supabase'

type Row = Record<string, any>
function Field({ label, name, type = 'text', required = true }: { label: string; name: string; type?: string; required?: boolean }) {
  return <label className="field"><span className="form-label">{label}</span><input name={name} type={type} required={required} /></label>
}
function Notice({ text }: { text: string }) { return text ? <div className="notice success">{text}</div> : null }
function Header({ title, eyebrow }: { title: string; eyebrow: string }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div></div> }
function State({ loading, error, empty, children }: { loading: boolean; error: string; empty?: boolean; children: React.ReactNode }) { if (loading) return <div className="panel state">Loading...</div>; if (error) return <div className="panel state error-state">{error}</div>; if (empty) return <div className="panel state">No records available yet.</div>; return <>{children}</> }
function useStudents() { const [state, setState] = useState({ data: [] as Row[], loading: true, error: '' }); const load = () => { if (!supabase) return setState({ data: [], loading: false, error: '' }); supabase.from('profiles').select('id,full_name,phone,email,student_code,educational_level,is_active').eq('role', 'student').order('created_at', { ascending: false }).then(({ data, error }) => setState({ data: data ?? [], loading: false, error: error?.message ?? '' })) }; useEffect(load, []); return { ...state, reload: load } }
function generateCode() { return `EZ-${Math.floor(100000 + Math.random() * 900000)}` }

export function TeacherStudentsPage() {
  const students = useStudents(); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState(''); const [search, setSearch] = useState('')
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!supabase) return setMessage('Connect Supabase to add students.'); const form = new FormData(event.currentTarget); const code = generateCode(); const result = await supabase.rpc('create_student_account', { p_email: form.get('email'), p_password: form.get('password'), p_full_name: form.get('full_name'), p_phone: form.get('phone'), p_level: form.get('educational_level'), p_student_code: code }); setMessage(result.error?.message ?? `Student created. Code: ${result.data?.student_code ?? code}`); if (!result.error) { students.reload(); event.currentTarget.reset(); setShowForm(false) } }
  const filtered = students.data.filter(student => `${student.full_name} ${student.email ?? ''} ${student.student_code ?? ''}`.toLowerCase().includes(search.toLowerCase()))
  return <><Header title="Students" eyebrow="Manage profiles, codes, and learning records" /><div className="toolbar"><input placeholder="Search by name, email, or code" value={search} onChange={event => setSearch(event.target.value)} /><button className="button" onClick={() => setShowForm(true)}><UserPlus size={17} /> Add Student</button></div>{showForm && <div className="panel modal-panel"><div className="modal-heading"><h3><UserPlus size={18} /> Add Student</h3><button className="icon-button" onClick={() => setShowForm(false)}><X size={17} /></button></div><form className="form-grid" onSubmit={save}><Field label="Full Name" name="full_name" /><Field label="Email" name="email" type="email" /><Field label="Temporary Password" name="password" type="password" /><Field label="Phone" name="phone" type="tel" required={false} /><Field label="Educational Level" name="educational_level" required={false} /><button className="button full-field">Create Student & Generate Code</button><Notice text={message} /></form></div>}<State loading={students.loading} error={students.error} empty={!students.loading && !filtered.length}><div className="data-table"><div className="data-row data-head"><span>Student</span><span>Code</span><span>Phone</span><span>Status</span></div>{filtered.map(student => <div className="data-row" key={student.id}><span><b>{student.full_name}</b><small>{student.email ?? '-'}</small></span><span className="status-badge">{student.student_code ?? 'Not assigned'}</span><span>{student.phone ?? '-'}</span><span>{student.is_active ? 'Active' : 'Inactive'}</span></div>)}</div></State></>
}

function QuestionEditor({ question, index, update, remove }: { question: Row; index: number; update: (index: number, key: string, value: any) => void; remove: (index: number) => void }) {
  return <div className="question-editor panel"><div className="modal-heading"><b>Question {index + 1}</b><button type="button" className="icon-button" onClick={() => remove(index)}><X size={15} /></button></div><label className="field"><span className="form-label">Question</span><textarea required value={question.prompt} onChange={event => update(index, 'prompt', event.target.value)} /></label><div className="form-grid">{['A', 'B', 'C', 'D'].map((option, optionIndex) => <label className="field" key={option}><span className="form-label">Option {option}</span><input required value={question.options?.[optionIndex] ?? ''} onChange={event => { const options = [...(question.options ?? [])]; options[optionIndex] = event.target.value; update(index, 'options', options) }} /></label>)}</div><label className="field"><span className="form-label">Correct Answer</span><select required value={question.correct_answer} onChange={event => update(index, 'correct_answer', event.target.value)}><option value="">Choose an option</option>{(question.options ?? []).map((option: string, optionIndex: number) => <option key={optionIndex} value={option}>{String.fromCharCode(65 + optionIndex)}: {option}</option>)}</select></label><label className="field"><span className="form-label">Marks</span><input type="number" min="1" value={question.marks} onChange={event => update(index, 'marks', event.target.value)} /></label></div>
}
export function TeacherExamsPage() {
  const [questions, setQuestions] = useState<Row[]>([]); const [courses, setCourses] = useState<Row[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { if (supabase) supabase.from('courses').select('id,name').eq('status', 'active').order('name').then(({ data }) => setCourses(data ?? [])) }, [])
  const updateQuestion = (index: number, key: string, value: string) => setQuestions(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!supabase) return setMessage('Connect Supabase to create exams.'); const user = await supabase.auth.getUser(); const form = new FormData(event.currentTarget); const exam = await supabase.from('exams').insert({ name: form.get('name'), description: form.get('description'), course_id: form.get('course_id'), exam_date: form.get('exam_date'), duration_minutes: form.get('duration_minutes'), total_marks: questions.reduce((sum, question) => sum + Number(question.marks ?? 1), 0), status: 'active' }).select().single(); if (exam.error || !exam.data) return setMessage(exam.error?.message ?? 'Unable to create exam.'); const rows = questions.map(question => ({ exam_id: exam.data.id, prompt: question.prompt, options: question.options ?? [], correct_answer: question.correct_answer, marks: Number(question.marks ?? 1) })); const result = rows.length ? await supabase.from('questions').insert(rows) : { error: null }; setMessage(result.error?.message ?? `Exam created with ${rows.length} question(s).`); if (!result.error) { event.currentTarget.reset(); setQuestions([]) } void user }
  return <><Header title="Exams" eyebrow="Create exams and add your own questions" /><form className="panel form-panel" onSubmit={submit}><h3><Plus size={18} /> Create Exam</h3><div className="form-grid"><Field label="Exam Name" name="name" /><label className="field"><span className="form-label">Course</span><select name="course_id" required><option value="">Choose a course</option>{courses.map(course => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><Field label="Exam Date" name="exam_date" type="datetime-local" required={false} /><Field label="Duration (minutes)" name="duration_minutes" type="number" required={false} /><label className="field full-field"><span className="form-label">Description</span><textarea name="description" /></label></div><div className="question-builder"><div className="modal-heading"><h3>Questions</h3><button type="button" className="button button-small" onClick={() => setQuestions(items => [...items, { prompt: '', correct_answer: '', marks: 1, options: [] }])}><Plus size={15} /> Add Question</button></div>{questions.length === 0 && <p className="muted">Add questions one by one. Each question supports four choices and a correct answer.</p>}{questions.map((question, index) => <QuestionEditor key={index} question={question} index={index} update={updateQuestion} remove={indexToRemove => setQuestions(items => items.filter((_, itemIndex) => itemIndex !== indexToRemove))} />)}</div><button className="button">Save Exam</button><Notice text={message} /></form></>
}
